### ISSUE TITLE
Fantastic news to hear that Potree can be run as executable. This could solve many problems with browser compataiblity issues.

### ISSUE THREAD

**Issue by robertdbuckley** [potree/PotreeDesktop#1]
This could solve many problems with browser compataiblity issues. Why is there no "material" setting for my point clouds? RGB, ELEVATION settings are missing? Do I have to activate this?

**Comment by robertdbuckley** [comment]
This could solve many problems with browser compataiblity issues.  Why is there no "material" setting for my point clouds? RGB, ELEVATION settings are missing? Do I have to activate this?

**Comment by potree** [comment]
Have you checked the Scene Panel? Material settings are now seperate for each point cloud, and therefore you'll have to select a point cloud to change them

![image](https://user-images.githubusercontent.com/2094934/37767337-14c7a68c-2dca-11e8-8274-96124518aa9a.png)

**Comment by robertdbuckley** [comment]
ah...you have to select the layer. Thanks
