### ISSUE TITLE
How to load converted point clouds

### ISSUE THREAD

**Issue by angussmitchell** [potree/PotreeDesktop#2]
I've successfully installed to Potree Desktop app, now I want to load my converted files up and view them. How do I do this? Can I file>open them from the desktop app somehow? or do I need to have them located in the desktop app folder? There doesn't seem to be any instruction about how to do this

Thanks

**Comment by m-schuetz** [comment]
You can drag&drop the cloud.js or the containing folder into the Potree Desktop window. Alternatively, you can modify the index.html file to load a specific point cloud from a path.

**Comment by angussmitchell** [comment]
Thanks for the feedback, a pretty dumb question, however it's not stated in the documentation. It would be great if the documentation could be improved
