### ISSUE TITLE
Incorrect area measurement of side wall

### ISSUE THREAD

**Issue by rajanidulal** [potree/PotreeDesktop#21]
Hello,

I am using PotreeDesktop to calculate the area of a room. While calculating the area of items on the floor or ceiling, it gives the correct measurement. However, when I tried to calculate the area of an item on the wall or from side view, it does not give me the correct area. I tried rotating and measuring from different angles but the area is still incorrect. Can anyone please help me through this?
![image](https://user-images.githubusercontent.com/56923694/94708907-b8ce0d80-030a-11eb-99a8-696b74f273ff.png)

Thank you!

**Comment by midnight-dev** [comment]
This is due to the core [Potree](https://github.com/potree/potree) area measurement only taking x & y coordinates into account. For reference, see the `getArea()` method found in `/src/utils/Measure.js` around L516.

**Comment by rajanidulal** [comment]
Got it. Thank you @midnight-dev
